---
title: "RESUME"
---

   Mr. Shaoxuan CHEN

E-mail: danielchansx@gmail.com

**EDUCATION**	  
Columbia University, New York, NY.
M.S., Biostatistics (Sept. 2017-May 2019(expected graduation))

South China Agricultural University (SCAU)	              Guangzhou, China
Undergraduate Program by School of Life Sciences	 09/2013-Present
Degree: Bachelor of Science in Biological Sciences anticipated in June 2017  
GPA: 3.77/5.0

**PUBLICATION & CONFERENCE PAPER**	    
Qingxun Ji, Shaoxuan Chen, Song Han, Yubo Cao, Rui Lu, Yongfu Dang, and Chuanling Qiao. Study on the Influence of NA-NY on the Drought Resistance of Germination and Seedling of Corn Seeds. Journal of Nuclear Agricultural Sciences. 2017, 31 (2): 348-354. 

Qingxun Ji, Shaoxuan Chen, Song Han, Yubo Cao, Yongfu Dang, and Chuanling Qiao. Study on the Germination and Growth of the Wheat Seeds Coated with Special Functional Additives. 2015 International Conference on Pesticide, Fertilizer and Seed in Shanghai, China, August 25-27, 2015

**PATENT**	  
Yongfu Dang, Shaoxuan Chen, Junzheng Qiu, Qingxun Ji, Song Han, and Chuanling Qiao. Preparation and Application of a Chinese Herbal Seed-dressing Agent: P.R. China, 201610993135.1 [P].  
(This patent application is accepted and the formal result will be announced in 2017.)

**RESEARCH**	  
Study on the Influence of NA-NY on the Drought Resistance of Germination and Seedling of Corn Seeds
Institution: Chinese Academy of Sciences                                                                                                                                                                          05/2016-08/2016

Collect data in test plots in Henan, Heilongjiang and Qinghai provinces, and collate data  
Read and sort out literature
Participate in experiment design 

Study on the Functions of Receptor-like Cytoplasmic Kinase VIII (RLCK VIII) in the Growth of Arabidopsis 
Institution: Plant Hormone Signal Transduction Laboratory (SCAU)                                                     03/2016-11/2016

Identify T-DNA insertional mutants of the RLCK VIII subfamily, and analyze the phenotypes both in embryonic 
and postembryonic development
Using promoter-GUS reporter lines to study the expression of RLCK genes in embryonic and postembryonic root development

Analyze the effect of exogenous auxin application on the root growth of the mutants
Screening of Rice Mutants
Institution: Plant Hormone Signal Transduction Laboratory (SCAU)                                                    10/2014-09/2015

Conduct statistical analysis on the possible mutants and wild-type rice
Screen mutants by comparing and processing data

**INTERNSHIP**	     
Naian Biological Technology Co., Ltd                                                                                                Zhengzhou, China
Statistical Analyst                                                                                                    07/2014-08/2014 & 06/2015-08/2015      
Conduct sales and market analysis (taking the influencing factors such as geographical locations, climates, and ripening time into account)
Collate, process and analyze the experimental data for product development 

**Other Experience**                                                                                      	      
Six Global Forum United Nations Alliance of Civilization                                                         Bali Island, Indonesia                           
Journalist                                                                                                                                                                 08/2015
Take photographs and sort out documents for the conferences 
Attend conferences given by officials from UN and governments, including UN Secretary-General Ban Ki-moon

Psychodrama, South China Agricultural University                                                                      Guangzhou, China                           
Director                                                                                                                                                                  10/2014
Take control of the planning and implementation of the psychodrama, e.g. selecting background music, script editing, rehearsal and stage design 

**Skills**	
Language: Native in Chinese (Mandarin). Fluent in Cantonese and English (TOEFL: 102; GRE: 320+3.0)

Software:R, Excel, PowerPoint, SigmaPlot
